// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Bubble: typeof import('./src/components/Bubble.vue')['default']
    BubbleMessage: typeof import('./src/components/BubbleMessage.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HiddenRefresh: typeof import('./src/components/HiddenRefresh.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    TButton: typeof import('./src/components/TButton.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TTransfer: typeof import('./src/components/TTransfer.vue')['default']
  }
}

export { }
